version: "3.9"

services:
  drone-app-db:
    container_name: drone_app_db
    image: postgres
    restart: always
    networks:
      - droneapp
    volumes:
      - droneapp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=drone_app

volumes:
  droneapp:
networks:
  droneapp: